/*
 * FogLAMP "Python 3.5" notification plugin.
 *
 * Copyright (c) 2018 Dianomic Systems
 *
 * Released under the Apache 2.0 Licence
 *
 * Author: Amandeep Singh Arora, Massimiliano Pinto
 */

#include <plugin_api.h>
#include <config_category.h>
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string>
#include <iostream>
#include <filter_plugin.h>
#include <filter.h>
#include <reading_set.h>
#include <utils.h>

#include <Python.h>
#include <version.h>

#include "notify_python35.h"

/**
 * The Python 3.5 script module to load is set in
 * 'script' config item and it doesn't need the trailing .py
 *
 * Example:
 * if filename is 'notify_alert.py', just set 'notify_alert'
 * via FogLAMP configuration manager
 *
 * Note:
 * Python 3.5 filter code needs only one method which accepts
 * a message string indicating notification trigger and processes 
 * the same as required.
 */

#define SCRIPT_NAME  "notify35"

// Delivery plugin default configuration
#define DEFAULT_CONFIG "{\"plugin\" : { \"description\" : \"Python 3.5 notification plugin\", " \
                       		"\"type\" : \"string\", " \
				"\"default\" : \"" PLUGIN_NAME "\", \"readonly\" : \"true\" }, " \
			 "\"enable\": {\"description\": \"A switch that can be used to enable or disable execution of " \
					 "the Python 3.5 notification plugin.\", " \
				"\"type\": \"boolean\", " \
				"\"displayName\" : \"Enabled\", " \
				"\"default\": \"false\" }, " \
			"\"config\" : {\"description\" : \"Python 3.5 filter configuration.\", " \
				"\"type\" : \"JSON\", " \
				"\"displayName\" : \"Configuration\", " \
				"\"default\" : {}}, " \
			"\"script\" : {\"description\" : \"Python 3.5 module to load.\", " \
				"\"type\": \"script\", " \
				"\"displayName\" : \"Python script\", " \
				"\"default\": \"" SCRIPT_NAME "\"} }"

using namespace std;

bool pythonInitialised = false;

/**
 * The Delivery plugin interface
 */
extern "C" {
/**
 * The plugin information structure
 */
static PLUGIN_INFORMATION info = {
        PLUGIN_NAME,                              // Name
        VERSION,                                  // Version
        0,                                        // Flags
        PLUGIN_TYPE_NOTIFICATION_DELIVERY,        // Type
        "1.0.0",                                  // Interface version
        DEFAULT_CONFIG	                          // Default plugin configuration
};

/**
 * Return the information about this plugin
 */
PLUGIN_INFORMATION *plugin_info()
{
	return &info;
}

/**
 * Initialise the plugin, called to get the plugin handle and setup the
 * output handle that will be passed to the output stream. The output stream
 * is merely a function pointer that is called with the output handle and
 * the new set of readings generated by the plugin.
 *     (*output)(outHandle, readings);
 * Note that the plugin may not call the output stream if the result of
 * the filtering is that no readings are to be sent onwards in the chain.
 * This allows the plugin to discard data or to buffer it for aggregation
 * with data that follows in subsequent calls
 *
 * @param config	The configuration category for the filter
 * @param outHandle	A handle that will be passed to the output stream
 * @param output	The output stream (function pointer) to which data is passed
 * @return		An opaque handle that is used in all subsequent calls to the plugin
 */
PLUGIN_HANDLE plugin_init(ConfigCategory* config)
{
	// Embedded Python 3.5 program name
	wchar_t *programName = Py_DecodeLocale(config->getName().c_str(), NULL);
	Py_SetProgramName(programName);
	PyMem_RawFree(programName);
	// Embedded Python 3.5 initialisation
	// Check first the interpreter is already set
	if (!Py_IsInitialized())
	{
		Py_Initialize();
		pythonInitialised = true;
	}

	// Instantiate plugin class
	NotifyPython35* notify = new NotifyPython35(config);
	// Add filters dir: pass FogLAMP Data dir
	notify->setScriptsPath(getDataDir());

	// Set Python path for embedded Python 3.5
	// Get current sys.path. borrowed reference
	PyObject* sysPath = PySys_GetObject((char *)string("path").c_str());
	// Add FogLAMP python filters path
	PyObject* pPath = PyUnicode_DecodeFSDefault((char *)notify->getScriptsPath().c_str());
	PyList_Insert(sysPath, 0, pPath);
	// Remove temp object
	Py_CLEAR(pPath);

	// Check first we have a Python script to load
	if (notify->getScriptName().empty())
	{
		// Force disable
		notify->disableDelivery();

		// Return filter handle
		return (PLUGIN_HANDLE)notify;
	}


	// Configure filter
	notify->lock();
	bool ret = notify->configure();
	notify->unlock();

	// Configure filter
	if (!ret)
	{
		// Cleanup Python 3.5
		if (pythonInitialised)
		{
			Py_Finalize();
		}

		// This will abort the filter pipeline set up
		return NULL;
	}
	else
	{
		// Return plugin handle
		return (PLUGIN_HANDLE)notify;
	}
}

/**
 * Deliver received notification data
 *
 * @param handle		The plugin handle returned from plugin_init
 * @param deliveryName		The delivery category name
 * @param notificationName	The notification name
 * @param triggerReason		The trigger reason for notification
 * @param message		The message from notification
 */
bool plugin_deliver(PLUGIN_HANDLE handle,
                    const std::string& deliveryName,
                    const std::string& notificationName,
                    const std::string& triggerReason,
                    const std::string& message)
{
	NotifyPython35* notify = (NotifyPython35 *) handle;

	return notify->notify(deliveryName,
			      notificationName,
			      triggerReason,
			      message);
}

/**
 * Call the shutdown method in the plugin
 */
void plugin_shutdown(PLUGIN_HANDLE *handle)
{
	NotifyPython35* notify = (NotifyPython35 *) handle;

	// Decrement pModule reference count
	Py_CLEAR(notify->m_pModule);
	// Decrement pFunc reference count
	Py_CLEAR(notify->m_pFunc);

	// Cleanup Python 3.5
	Py_Finalize();

	// Cleanup memory
	delete notify;
}

/**
 * Reconfigure the plugin
 */
void plugin_reconfigure(PLUGIN_HANDLE *handle,
			string& newConfig)
{
	NotifyPython35* notify = (NotifyPython35 *)handle;
	
	notify->reconfigure(newConfig);
}

// End of extern "C"
};
